channel: '#sra-builds'
clone:
  tags: true
workflows:
  publish:
    on: farm
    pipeline:
      publish:
        image: hub.terra.songsterr.com/builderr-android
        commands:
          - ./gradlew publish --stacktrace
